import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F5F7FB',
  },
  container: {
    gap: 18,
    padding: 20,
    paddingBottom: 32,
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  headerMeta: {
    color: '#4B5563',
    fontSize: 14,
    fontWeight: '800',
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#E5E7EB',
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  secondaryButtonWide: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#E5E7EB',
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 13,
    width: '100%',
  },
  secondaryButtonPressed: {
    backgroundColor: '#F3F4F6',
    borderColor: '#CBD5E1',
  },
  secondaryButtonText: {
    color: '#111827',
    fontSize: 14,
    fontWeight: '800',
  },
  progressTrack: {
    backgroundColor: '#E5E7EB',
    borderRadius: 999,
    height: 10,
    overflow: 'hidden',
  },
  progressFill: {
    backgroundColor: '#2563EB',
    borderRadius: 999,
    height: '100%',
  },
  questionCard: {
    backgroundColor: '#111827',
    borderRadius: 8,
    padding: 20,
  },
  topicLabel: {
    color: '#93C5FD',
    fontSize: 14,
    fontWeight: '800',
    marginBottom: 12,
    textTransform: 'uppercase',
  },
  questionText: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '800',
    lineHeight: 31,
  },
  difficultyBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#1F2937',
    borderColor: '#374151',
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 16,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  difficultyText: {
    color: '#D1D5DB',
    fontSize: 13,
    fontWeight: '800',
  },
  answerList: {
    gap: 10,
  },
  answerButton: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E5E7EB',
    borderRadius: 8,
    borderWidth: 1,
    padding: 16,
  },
  answerButtonPressed: {
    backgroundColor: '#F8FAFC',
  },
  answerButtonSelected: {
    backgroundColor: '#DBEAFE',
    borderColor: '#2563EB',
  },
  answerText: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 22,
  },
  answerTextSelected: {
    color: '#1D4ED8',
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#2563EB',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  primaryButtonPressed: {
    backgroundColor: '#1D4ED8',
  },
  primaryButtonDisabled: {
    backgroundColor: '#93C5FD',
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
  },
  resultContainer: {
    gap: 16,
    padding: 20,
    paddingBottom: 32,
  },
  resultEyebrow: {
    color: '#2563EB',
    fontSize: 14,
    fontWeight: '800',
    marginTop: 8,
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  resultTitle: {
    color: '#111827',
    fontSize: 56,
    fontWeight: '900',
    lineHeight: 62,
    textAlign: 'center',
  },
  resultSubtitle: {
    color: '#4B5563',
    fontSize: 16,
    lineHeight: 23,
    marginBottom: 2,
    textAlign: 'center',
  },
  resultStatsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  resultStatCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E5E7EB',
    borderRadius: 8,
    borderWidth: 1,
    flexBasis: '31%',
    flexGrow: 1,
    minWidth: 112,
    padding: 14,
  },
  resultStatLabel: {
    color: '#6B7280',
    fontSize: 12,
    fontWeight: '800',
  },
  resultStatValue: {
    color: '#111827',
    fontSize: 22,
    fontWeight: '900',
    lineHeight: 28,
    marginTop: 8,
  },
  resultStatHelper: {
    color: '#6B7280',
    fontSize: 11,
    lineHeight: 15,
    marginTop: 4,
  },
  resultSection: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E5E7EB',
    borderRadius: 8,
    borderWidth: 1,
    padding: 16,
  },
  resultSectionTitle: {
    color: '#111827',
    fontSize: 18,
    fontWeight: '900',
    marginBottom: 12,
  },
  resultSectionEmpty: {
    color: '#6B7280',
    fontSize: 14,
    lineHeight: 20,
  },
  resultTopicItem: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    paddingVertical: 8,
  },
  resultTopicTextGroup: {
    flex: 1,
  },
  resultTopicLabel: {
    color: '#111827',
    fontSize: 15,
    fontWeight: '800',
  },
  resultTopicMeta: {
    color: '#6B7280',
    fontSize: 12,
    marginTop: 3,
  },
  resultTopicScore: {
    color: '#2563EB',
    fontSize: 15,
    fontWeight: '900',
  },
  resultActions: {
    gap: 10,
    marginTop: 2,
  },
});
