import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F5F7FB',
  },
  container: {
    gap: 18,
    padding: 20,
    paddingBottom: 32,
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  eyebrow: {
    color: '#2563EB',
    fontSize: 14,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  title: {
    color: '#111827',
    fontSize: 28,
    fontWeight: '800',
    marginTop: 4,
  },
  streakBadge: {
    alignItems: 'center',
    backgroundColor: '#FEF3C7',
    borderRadius: 8,
    minWidth: 58,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  streakValue: {
    color: '#92400E',
    fontSize: 18,
    fontWeight: '800',
  },
  streakLabel: {
    color: '#92400E',
    fontSize: 12,
    fontWeight: '600',
  },
  hero: {
    backgroundColor: '#111827',
    borderRadius: 8,
    padding: 20,
  },
  heroLabel: {
    color: '#93C5FD',
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 6,
  },
  heroTitle: {
    color: '#FFFFFF',
    fontSize: 26,
    fontWeight: '800',
  },
  heroSubtitle: {
    color: '#D1D5DB',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 8,
  },
  progressTrack: {
    backgroundColor: '#374151',
    borderRadius: 999,
    height: 10,
    marginTop: 18,
    overflow: 'hidden',
  },
  progressFill: {
    backgroundColor: '#22C55E',
    borderRadius: 999,
    height: '100%',
  },
  progressCaption: {
    color: '#D1D5DB',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 8,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  metricCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E5E7EB',
    borderRadius: 8,
    borderWidth: 1,
    flexBasis: '31%',
    flexGrow: 1,
    minWidth: 104,
    padding: 14,
  },
  metricLabel: {
    color: '#6B7280',
    fontSize: 12,
    fontWeight: '700',
  },
  metricValue: {
    color: '#111827',
    fontSize: 21,
    fontWeight: '800',
    lineHeight: 27,
    marginTop: 8,
  },
  metricHelper: {
    color: '#6B7280',
    fontSize: 11,
    lineHeight: 15,
    marginTop: 4,
  },
  section: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E5E7EB',
    borderRadius: 8,
    borderWidth: 1,
    padding: 16,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    color: '#111827',
    fontSize: 20,
    fontWeight: '800',
  },
  sectionMeta: {
    color: '#2563EB',
    fontSize: 13,
    fontWeight: '800',
  },
  sectionDescription: {
    color: '#4B5563',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 8,
  },
  taskList: {
    gap: 10,
    marginTop: 14,
  },
  taskItem: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  taskCheck: {
    borderColor: '#CBD5E1',
    borderRadius: 5,
    borderWidth: 2,
    height: 20,
    width: 20,
  },
  taskCheckDone: {
    backgroundColor: '#22C55E',
    borderColor: '#22C55E',
  },
  taskText: {
    color: '#111827',
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
  },
  taskTextDone: {
    color: '#6B7280',
    textDecorationLine: 'line-through',
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#2563EB',
    borderRadius: 8,
    marginTop: 16,
    paddingHorizontal: 16,
    paddingVertical: 13,
  },
  primaryButtonPressed: {
    backgroundColor: '#1D4ED8',
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
  },
  topicsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  topicPanel: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E5E7EB',
    borderRadius: 8,
    borderWidth: 1,
    flexBasis: '48%',
    flexGrow: 1,
    minWidth: 240,
    padding: 16,
  },
  topicTitle: {
    color: '#111827',
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 12,
  },
  topicItem: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    marginBottom: 12,
  },
  topicDot: {
    borderRadius: 999,
    height: 10,
    width: 10,
  },
  successDot: {
    backgroundColor: '#16A34A',
  },
  warningDot: {
    backgroundColor: '#F59E0B',
  },
  topicContent: {
    flex: 1,
  },
  topicLabel: {
    color: '#111827',
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 6,
  },
  topicTrack: {
    backgroundColor: '#E5E7EB',
    borderRadius: 999,
    height: 6,
    overflow: 'hidden',
  },
  topicFill: {
    backgroundColor: '#2563EB',
    borderRadius: 999,
    height: '100%',
  },
  topicScore: {
    color: '#4B5563',
    fontSize: 13,
    fontWeight: '800',
    textAlign: 'center',
  },
});
